# Generated by Django 4.2.12 on 2025-03-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_in_profile',
            field=models.BooleanField(default=False, verbose_name='В профиле'),
        ),
    ]
