# Generated by Django 4.2.12 on 2025-03-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_alter_breed_options_alter_dog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='description',
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название породы'),
        ),
    ]
