# Generated by Django 4.2.12 on 2025-03-31 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogs', '0005_remove_breed_description_alter_breed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
