# Generated by Django 4.2.12 on 2025-04-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_breed_description_breed_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['breed'], name='dog_breed_idx'),
        ),
    ]
