# Generated by Django 4.2.12 on 2025-04-27 12:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogs', '0010_dog_dog_breed_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dogs.dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отец')),
                ('mother', models.CharField(blank=True, max_length=100, null=True, verbose_name='Мать')),
                ('grand_father_father', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дед по отцу')),
                ('grand_mother_father', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бабушка по отцу')),
                ('grand_father_mother', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дед по матери')),
                ('grand_mother_mother', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бабушка по матери')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigrees', to='dogs.dog', verbose_name='Собака')),
            ],
            options={
                'verbose_name': 'Родословная',
                'verbose_name_plural': 'Родословные',
            },
        ),
    ]
