# Generated by Django 4.2.12 on 2025-04-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0012_alter_review_options_dog_active_dog_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveField(
            model_name='dog',
            name='active',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='views',
        ),
        migrations.AddField(
            model_name='dog',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
